# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c61cf5d410f31a512827b52af1fdbeb4676f341009497d039c3594908ec55af0debf35cac2d5fcb25e9ac0c17610882ce81899358757058758d5ace37efd8a83

test:
  secret_key_base: 642f5bac20928e0806c0f09a9e997693baceb0b07ed3e8cafc92484aa71103442f8a8955367440a607a425d10aa546421f8b66430de36ee365389d3e395dc240

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
